services:
  reservation_service:
    image: node:21
    container_name: reservation_service
    working_dir: /app
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./.env:/app/.env
    ports:
      - '3001:3000'
    command: ['node', 'dist/main.js']
    networks:
      - hotel-reservation-system_hrs_network
    restart: 'no'

networks:
  hotel-reservation-system_hrs_network:
    driver: bridge
    external: true
